[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[dependencies]
forge-std = { git = "https://github.com/foundry-rs/forge-std", tag = "v1.10.0" }
openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts", tag = "v5.4.0" }
